osx_image: xcode9.1
rvm: 2.3
language: objective-c
cache:
  - cocoapods
  - bundler
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle update
  - pod repo update
script:
  - sh ./fastlane/decrypt_p12.sh
  - bundle exec fastlane release
  - bundle exec fastlane beta
  - bundle exec fastlane release_previewer
notifications:
  slack: yumimobi:wCaD46mZfHIPfiI6guogLeWB
env:
  global:
  - secure: LZf9MlvotDSj13YBekKcjaDxbmTJmFychu8YXjd/qjbv+rH1Zd07G8gdWf21c+zgBjv5iShm8QPt9MtJWx6zC8M2/qZj1ryw5fTWZJchbYEiiWWTXtlnbXSxRYUXL9xHGMrcBmvRkj9Dn52PwYCE7SmdmhaQnL6CGmbE8RKAudmsw03Cw1DVf0Bcha2XAZ4M7iVeU6hDsEPF5lvZF6BM5mzsLJGGtvbD79g45UidvK8zd3S7jEpK2XsAfEF0FxVKfpGj39e23KjzwZnYrSllqOGcE6infvQ7lclSnbKuENz/aIq1k6iVCGdEXpr2lg8mXlQnq81OKu70zPZ7egvnubm8Jre32VJj5PoljCEf5ueD58SodvBWKOY+4RO4/GLXWeALjLTCe8Fw668blTGXtYy8CUyU79yaAwLk4r4fz7V8gWPalXkwHqxjS1bye208777KKeyMB1ztFGuM/MLrrIN4wVT+fMngxQ8vWQisZ20fQujh23JJOBKOPT9RMHz83ZD6j95Fzd/9Svakq3CL4iGZ8eR4hwonqLTFnWSoPTN2a96XX33S36+VQaCR0baX4WiJUh41KznYVdlTrrGmhUsc9A1NqEGM1odBr9qhiJX0jvOJ1Ava93fI3XfOXIxFyZ1IGLvMbVX1vJ8a9uGFVmiTnIzpSOu/dzDOEBytAnE=
